import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hostel Daze',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <div className="w-full  flex justify-center items-center ">
        <div className=" w-3/4 flex justify-center items-center flex-col ">
          {children}

        </div>
      </div>


      <Footer/>
      </body>
    </html>
  )
}
